# Generated by Django 5.1.3 on 2024-12-24 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_rename_total_quiz_count_course_total_text_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_id',
        ),
    ]
