# Generated by Django 5.1.3 on 2024-12-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_certificate_certificate_id'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='joined_courses', to='user.student'),
        ),
    ]
